#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
#
# e.g. ./create "shutdown:idle" "Package Manager" "Upgrade in Progress..." "block"



from __future__ import print_function

import os, sys
display = os.environ.get('DISPLAY') != None

import subprocess

def inhibit(argv):
    (what, who, why, mode) = argv
    response_from_dbus = send_dbus("Inhibit", what, who, why, mode)
    return response_from_dbus
                
def send_dbus(method, what, who, why, mode):
    arguments = ["dbus-send",
                 "--print-reply",
                 "--system",
                 "--dest=org.freedesktop.login1",
                 "/org/freedesktop/login1",
                 "org.freedesktop.login1.Manager.{}".format(method),
                 "string:{}".format(what),
                 "string:{}".format(who),
                 "string:{}".format(why),
                 "string:{}".format(mode) ]
    response = subprocess.check_output(arguments)
    return response

def main(argv):
    fd = inhibit(argv),
    
if __name__ == "__main__":
    main(sys.argv[1:])
    sys.exit(0)
