#!/usr/bin/env python2.7
# -*- coding: utf-8 -*-
from __future__ import print_function

import os, sys
display = os.environ.get('DISPLAY') != None

import subprocess
                
def send_dbus(method):
    arguments = ["dbus-send",
                 "--print-reply",
                 "--system",
                 "--dest=org.freedesktop.login1",
                 "/org/freedesktop/login1",
                 "org.freedesktop.login1.Manager.{}".format(method)]
    response = subprocess.check_output(arguments)
    return response

def main(argv):
    result = send_dbus("ListInhibitors")
    print (result)
    
if __name__ == "__main__":
    main(sys.argv[1:])
    sys.exit(0)
